FROM ghcr.io/huggingface/text-generation-inference:2.4.0

ENV MODEL_ID=Shuvam-Maity/edututor-mistral-awq
ENV QUANTIZE=awq
ENV MAX_INPUT_LENGTH=512
ENV MAX_TOTAL_TOKENS=1024
ENV PORT=7860
ENV AWQ_VERSION=gemv